/*
 * This file is generated by jOOQ.
 */
package generation.tables.records;


import generation.tables.Action;

import java.time.LocalDate;

import org.jooq.Field;
import org.jooq.Record4;
import org.jooq.Row4;
import org.jooq.impl.TableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class ActionRecord extends TableRecordImpl<ActionRecord> implements Record4<String, LocalDate, Integer, Integer> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>public.action.commentaire</code>.
     */
    public void setCommentaire(String value) {
        set(0, value);
    }

    /**
     * Getter for <code>public.action.commentaire</code>.
     */
    public String getCommentaire() {
        return (String) get(0);
    }

    /**
     * Setter for <code>public.action.date_action</code>.
     */
    public void setDateAction(LocalDate value) {
        set(1, value);
    }

    /**
     * Getter for <code>public.action.date_action</code>.
     */
    public LocalDate getDateAction() {
        return (LocalDate) get(1);
    }

    /**
     * Setter for <code>public.action.id_user</code>.
     */
    public void setIdUser(Integer value) {
        set(2, value);
    }

    /**
     * Getter for <code>public.action.id_user</code>.
     */
    public Integer getIdUser() {
        return (Integer) get(2);
    }

    /**
     * Setter for <code>public.action.id</code>.
     */
    public void setId(Integer value) {
        set(3, value);
    }

    /**
     * Getter for <code>public.action.id</code>.
     */
    public Integer getId() {
        return (Integer) get(3);
    }

    // -------------------------------------------------------------------------
    // Record4 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row4<String, LocalDate, Integer, Integer> fieldsRow() {
        return (Row4) super.fieldsRow();
    }

    @Override
    public Row4<String, LocalDate, Integer, Integer> valuesRow() {
        return (Row4) super.valuesRow();
    }

    @Override
    public Field<String> field1() {
        return Action.ACTION.COMMENTAIRE;
    }

    @Override
    public Field<LocalDate> field2() {
        return Action.ACTION.DATE_ACTION;
    }

    @Override
    public Field<Integer> field3() {
        return Action.ACTION.ID_USER;
    }

    @Override
    public Field<Integer> field4() {
        return Action.ACTION.ID;
    }

    @Override
    public String component1() {
        return getCommentaire();
    }

    @Override
    public LocalDate component2() {
        return getDateAction();
    }

    @Override
    public Integer component3() {
        return getIdUser();
    }

    @Override
    public Integer component4() {
        return getId();
    }

    @Override
    public String value1() {
        return getCommentaire();
    }

    @Override
    public LocalDate value2() {
        return getDateAction();
    }

    @Override
    public Integer value3() {
        return getIdUser();
    }

    @Override
    public Integer value4() {
        return getId();
    }

    @Override
    public ActionRecord value1(String value) {
        setCommentaire(value);
        return this;
    }

    @Override
    public ActionRecord value2(LocalDate value) {
        setDateAction(value);
        return this;
    }

    @Override
    public ActionRecord value3(Integer value) {
        setIdUser(value);
        return this;
    }

    @Override
    public ActionRecord value4(Integer value) {
        setId(value);
        return this;
    }

    @Override
    public ActionRecord values(String value1, LocalDate value2, Integer value3, Integer value4) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached ActionRecord
     */
    public ActionRecord() {
        super(Action.ACTION);
    }

    /**
     * Create a detached, initialised ActionRecord
     */
    public ActionRecord(String commentaire, LocalDate dateAction, Integer idUser, Integer id) {
        super(Action.ACTION);

        setCommentaire(commentaire);
        setDateAction(dateAction);
        setIdUser(idUser);
        setId(id);
    }
}
