/*
 * This file is generated by jOOQ.
 */
package generation.tables.records;


import generation.tables.ApplicationUser;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record6;
import org.jooq.Row6;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class ApplicationUserRecord extends UpdatableRecordImpl<ApplicationUserRecord> implements Record6<Integer, String, String, String, String, Boolean> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>public.application_user.id</code>.
     */
    public void setId(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>public.application_user.id</code>.
     */
    public Integer getId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>public.application_user.username</code>.
     */
    public void setUsername(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>public.application_user.username</code>.
     */
    public String getUsername() {
        return (String) get(1);
    }

    /**
     * Setter for <code>public.application_user.nom</code>.
     */
    public void setNom(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>public.application_user.nom</code>.
     */
    public String getNom() {
        return (String) get(2);
    }

    /**
     * Setter for <code>public.application_user.password</code>.
     */
    public void setPassword(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>public.application_user.password</code>.
     */
    public String getPassword() {
        return (String) get(3);
    }

    /**
     * Setter for <code>public.application_user.mail</code>.
     */
    public void setMail(String value) {
        set(4, value);
    }

    /**
     * Getter for <code>public.application_user.mail</code>.
     */
    public String getMail() {
        return (String) get(4);
    }

    /**
     * Setter for <code>public.application_user.actif</code>.
     */
    public void setActif(Boolean value) {
        set(5, value);
    }

    /**
     * Getter for <code>public.application_user.actif</code>.
     */
    public Boolean getActif() {
        return (Boolean) get(5);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record6 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row6<Integer, String, String, String, String, Boolean> fieldsRow() {
        return (Row6) super.fieldsRow();
    }

    @Override
    public Row6<Integer, String, String, String, String, Boolean> valuesRow() {
        return (Row6) super.valuesRow();
    }

    @Override
    public Field<Integer> field1() {
        return ApplicationUser.APPLICATION_USER.ID;
    }

    @Override
    public Field<String> field2() {
        return ApplicationUser.APPLICATION_USER.USERNAME;
    }

    @Override
    public Field<String> field3() {
        return ApplicationUser.APPLICATION_USER.NOM;
    }

    @Override
    public Field<String> field4() {
        return ApplicationUser.APPLICATION_USER.PASSWORD;
    }

    @Override
    public Field<String> field5() {
        return ApplicationUser.APPLICATION_USER.MAIL;
    }

    @Override
    public Field<Boolean> field6() {
        return ApplicationUser.APPLICATION_USER.ACTIF;
    }

    @Override
    public Integer component1() {
        return getId();
    }

    @Override
    public String component2() {
        return getUsername();
    }

    @Override
    public String component3() {
        return getNom();
    }

    @Override
    public String component4() {
        return getPassword();
    }

    @Override
    public String component5() {
        return getMail();
    }

    @Override
    public Boolean component6() {
        return getActif();
    }

    @Override
    public Integer value1() {
        return getId();
    }

    @Override
    public String value2() {
        return getUsername();
    }

    @Override
    public String value3() {
        return getNom();
    }

    @Override
    public String value4() {
        return getPassword();
    }

    @Override
    public String value5() {
        return getMail();
    }

    @Override
    public Boolean value6() {
        return getActif();
    }

    @Override
    public ApplicationUserRecord value1(Integer value) {
        setId(value);
        return this;
    }

    @Override
    public ApplicationUserRecord value2(String value) {
        setUsername(value);
        return this;
    }

    @Override
    public ApplicationUserRecord value3(String value) {
        setNom(value);
        return this;
    }

    @Override
    public ApplicationUserRecord value4(String value) {
        setPassword(value);
        return this;
    }

    @Override
    public ApplicationUserRecord value5(String value) {
        setMail(value);
        return this;
    }

    @Override
    public ApplicationUserRecord value6(Boolean value) {
        setActif(value);
        return this;
    }

    @Override
    public ApplicationUserRecord values(Integer value1, String value2, String value3, String value4, String value5, Boolean value6) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached ApplicationUserRecord
     */
    public ApplicationUserRecord() {
        super(ApplicationUser.APPLICATION_USER);
    }

    /**
     * Create a detached, initialised ApplicationUserRecord
     */
    public ApplicationUserRecord(Integer id, String username, String nom, String password, String mail, Boolean actif) {
        super(ApplicationUser.APPLICATION_USER);

        setId(id);
        setUsername(username);
        setNom(nom);
        setPassword(password);
        setMail(mail);
        setActif(actif);
    }
}
