/*
 * This file is generated by jOOQ.
 */
package generation.tables.records;


import generation.tables.Auteur;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record3;
import org.jooq.Row3;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class AuteurRecord extends UpdatableRecordImpl<AuteurRecord> implements Record3<Integer, String, String> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>PUBLIC.AUTEUR.ID</code>.
     */
    public void setId(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>PUBLIC.AUTEUR.ID</code>.
     */
    public Integer getId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>PUBLIC.AUTEUR.NOM</code>.
     */
    public void setNom(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>PUBLIC.AUTEUR.NOM</code>.
     */
    public String getNom() {
        return (String) get(1);
    }

    /**
     * Setter for <code>PUBLIC.AUTEUR.PRENOM</code>.
     */
    public void setPrenom(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>PUBLIC.AUTEUR.PRENOM</code>.
     */
    public String getPrenom() {
        return (String) get(2);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record3 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row3<Integer, String, String> fieldsRow() {
        return (Row3) super.fieldsRow();
    }

    @Override
    public Row3<Integer, String, String> valuesRow() {
        return (Row3) super.valuesRow();
    }

    @Override
    public Field<Integer> field1() {
        return Auteur.AUTEUR.ID;
    }

    @Override
    public Field<String> field2() {
        return Auteur.AUTEUR.NOM;
    }

    @Override
    public Field<String> field3() {
        return Auteur.AUTEUR.PRENOM;
    }

    @Override
    public Integer component1() {
        return getId();
    }

    @Override
    public String component2() {
        return getNom();
    }

    @Override
    public String component3() {
        return getPrenom();
    }

    @Override
    public Integer value1() {
        return getId();
    }

    @Override
    public String value2() {
        return getNom();
    }

    @Override
    public String value3() {
        return getPrenom();
    }

    @Override
    public AuteurRecord value1(Integer value) {
        setId(value);
        return this;
    }

    @Override
    public AuteurRecord value2(String value) {
        setNom(value);
        return this;
    }

    @Override
    public AuteurRecord value3(String value) {
        setPrenom(value);
        return this;
    }

    @Override
    public AuteurRecord values(Integer value1, String value2, String value3) {
        value1(value1);
        value2(value2);
        value3(value3);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached AuteurRecord
     */
    public AuteurRecord() {
        super(Auteur.AUTEUR);
    }

    /**
     * Create a detached, initialised AuteurRecord
     */
    public AuteurRecord(Integer id, String nom, String prenom) {
        super(Auteur.AUTEUR);

        setId(id);
        setNom(nom);
        setPrenom(prenom);
    }
}
