/*
 * This file is generated by jOOQ.
 */
package generation.tables.records;


import generation.tables.Livre;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record5;
import org.jooq.Row5;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class LivreRecord extends UpdatableRecordImpl<LivreRecord> implements Record5<Integer, String, String, Integer, Integer> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>PUBLIC.LIVRE.ID</code>.
     */
    public void setId(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>PUBLIC.LIVRE.ID</code>.
     */
    public Integer getId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>PUBLIC.LIVRE.NOM</code>.
     */
    public void setNom(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>PUBLIC.LIVRE.NOM</code>.
     */
    public String getNom() {
        return (String) get(1);
    }

    /**
     * Setter for <code>PUBLIC.LIVRE.LANGUE</code>.
     */
    public void setLangue(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>PUBLIC.LIVRE.LANGUE</code>.
     */
    public String getLangue() {
        return (String) get(2);
    }

    /**
     * Setter for <code>PUBLIC.LIVRE.ID_AUTEUR</code>.
     */
    public void setIdAuteur(Integer value) {
        set(3, value);
    }

    /**
     * Getter for <code>PUBLIC.LIVRE.ID_AUTEUR</code>.
     */
    public Integer getIdAuteur() {
        return (Integer) get(3);
    }

    /**
     * Setter for <code>PUBLIC.LIVRE.ID_PROFILE</code>.
     */
    public void setIdProfile(Integer value) {
        set(4, value);
    }

    /**
     * Getter for <code>PUBLIC.LIVRE.ID_PROFILE</code>.
     */
    public Integer getIdProfile() {
        return (Integer) get(4);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record5 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row5<Integer, String, String, Integer, Integer> fieldsRow() {
        return (Row5) super.fieldsRow();
    }

    @Override
    public Row5<Integer, String, String, Integer, Integer> valuesRow() {
        return (Row5) super.valuesRow();
    }

    @Override
    public Field<Integer> field1() {
        return Livre.LIVRE.ID;
    }

    @Override
    public Field<String> field2() {
        return Livre.LIVRE.NOM;
    }

    @Override
    public Field<String> field3() {
        return Livre.LIVRE.LANGUE;
    }

    @Override
    public Field<Integer> field4() {
        return Livre.LIVRE.ID_AUTEUR;
    }

    @Override
    public Field<Integer> field5() {
        return Livre.LIVRE.ID_PROFILE;
    }

    @Override
    public Integer component1() {
        return getId();
    }

    @Override
    public String component2() {
        return getNom();
    }

    @Override
    public String component3() {
        return getLangue();
    }

    @Override
    public Integer component4() {
        return getIdAuteur();
    }

    @Override
    public Integer component5() {
        return getIdProfile();
    }

    @Override
    public Integer value1() {
        return getId();
    }

    @Override
    public String value2() {
        return getNom();
    }

    @Override
    public String value3() {
        return getLangue();
    }

    @Override
    public Integer value4() {
        return getIdAuteur();
    }

    @Override
    public Integer value5() {
        return getIdProfile();
    }

    @Override
    public LivreRecord value1(Integer value) {
        setId(value);
        return this;
    }

    @Override
    public LivreRecord value2(String value) {
        setNom(value);
        return this;
    }

    @Override
    public LivreRecord value3(String value) {
        setLangue(value);
        return this;
    }

    @Override
    public LivreRecord value4(Integer value) {
        setIdAuteur(value);
        return this;
    }

    @Override
    public LivreRecord value5(Integer value) {
        setIdProfile(value);
        return this;
    }

    @Override
    public LivreRecord values(Integer value1, String value2, String value3, Integer value4, Integer value5) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached LivreRecord
     */
    public LivreRecord() {
        super(Livre.LIVRE);
    }

    /**
     * Create a detached, initialised LivreRecord
     */
    public LivreRecord(Integer id, String nom, String langue, Integer idAuteur, Integer idProfile) {
        super(Livre.LIVRE);

        setId(id);
        setNom(nom);
        setLangue(langue);
        setIdAuteur(idAuteur);
        setIdProfile(idProfile);
    }
}
