/*
 * This file is generated by jOOQ.
 */
package generation.tables.records;


import generation.tables.Livre;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record7;
import org.jooq.Row7;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class LivreRecord extends UpdatableRecordImpl<LivreRecord> implements Record7<Integer, String, String, Integer, Integer, Integer, Integer> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>public.livre.id</code>.
     */
    public void setId(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>public.livre.id</code>.
     */
    public Integer getId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>public.livre.nom</code>.
     */
    public void setNom(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>public.livre.nom</code>.
     */
    public String getNom() {
        return (String) get(1);
    }

    /**
     * Setter for <code>public.livre.langue</code>.
     */
    public void setLangue(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>public.livre.langue</code>.
     */
    public String getLangue() {
        return (String) get(2);
    }

    /**
     * Setter for <code>public.livre.id_auteur</code>.
     */
    public void setIdAuteur(Integer value) {
        set(3, value);
    }

    /**
     * Getter for <code>public.livre.id_auteur</code>.
     */
    public Integer getIdAuteur() {
        return (Integer) get(3);
    }

    /**
     * Setter for <code>public.livre.id_profil</code>.
     */
    public void setIdProfil(Integer value) {
        set(4, value);
    }

    /**
     * Getter for <code>public.livre.id_profil</code>.
     */
    public Integer getIdProfil() {
        return (Integer) get(4);
    }

    /**
     * Setter for <code>public.livre.id_stock</code>.
     */
    public void setIdStock(Integer value) {
        set(5, value);
    }

    /**
     * Getter for <code>public.livre.id_stock</code>.
     */
    public Integer getIdStock() {
        return (Integer) get(5);
    }

    /**
     * Setter for <code>public.livre.prix</code>.
     */
    public void setPrix(Integer value) {
        set(6, value);
    }

    /**
     * Getter for <code>public.livre.prix</code>.
     */
    public Integer getPrix() {
        return (Integer) get(6);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record7 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row7<Integer, String, String, Integer, Integer, Integer, Integer> fieldsRow() {
        return (Row7) super.fieldsRow();
    }

    @Override
    public Row7<Integer, String, String, Integer, Integer, Integer, Integer> valuesRow() {
        return (Row7) super.valuesRow();
    }

    @Override
    public Field<Integer> field1() {
        return Livre.LIVRE.ID;
    }

    @Override
    public Field<String> field2() {
        return Livre.LIVRE.NOM;
    }

    @Override
    public Field<String> field3() {
        return Livre.LIVRE.LANGUE;
    }

    @Override
    public Field<Integer> field4() {
        return Livre.LIVRE.ID_AUTEUR;
    }

    @Override
    public Field<Integer> field5() {
        return Livre.LIVRE.ID_PROFIL;
    }

    @Override
    public Field<Integer> field6() {
        return Livre.LIVRE.ID_STOCK;
    }

    @Override
    public Field<Integer> field7() {
        return Livre.LIVRE.PRIX;
    }

    @Override
    public Integer component1() {
        return getId();
    }

    @Override
    public String component2() {
        return getNom();
    }

    @Override
    public String component3() {
        return getLangue();
    }

    @Override
    public Integer component4() {
        return getIdAuteur();
    }

    @Override
    public Integer component5() {
        return getIdProfil();
    }

    @Override
    public Integer component6() {
        return getIdStock();
    }

    @Override
    public Integer component7() {
        return getPrix();
    }

    @Override
    public Integer value1() {
        return getId();
    }

    @Override
    public String value2() {
        return getNom();
    }

    @Override
    public String value3() {
        return getLangue();
    }

    @Override
    public Integer value4() {
        return getIdAuteur();
    }

    @Override
    public Integer value5() {
        return getIdProfil();
    }

    @Override
    public Integer value6() {
        return getIdStock();
    }

    @Override
    public Integer value7() {
        return getPrix();
    }

    @Override
    public LivreRecord value1(Integer value) {
        setId(value);
        return this;
    }

    @Override
    public LivreRecord value2(String value) {
        setNom(value);
        return this;
    }

    @Override
    public LivreRecord value3(String value) {
        setLangue(value);
        return this;
    }

    @Override
    public LivreRecord value4(Integer value) {
        setIdAuteur(value);
        return this;
    }

    @Override
    public LivreRecord value5(Integer value) {
        setIdProfil(value);
        return this;
    }

    @Override
    public LivreRecord value6(Integer value) {
        setIdStock(value);
        return this;
    }

    @Override
    public LivreRecord value7(Integer value) {
        setPrix(value);
        return this;
    }

    @Override
    public LivreRecord values(Integer value1, String value2, String value3, Integer value4, Integer value5, Integer value6, Integer value7) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached LivreRecord
     */
    public LivreRecord() {
        super(Livre.LIVRE);
    }

    /**
     * Create a detached, initialised LivreRecord
     */
    public LivreRecord(Integer id, String nom, String langue, Integer idAuteur, Integer idProfil, Integer idStock, Integer prix) {
        super(Livre.LIVRE);

        setId(id);
        setNom(nom);
        setLangue(langue);
        setIdAuteur(idAuteur);
        setIdProfil(idProfil);
        setIdStock(idStock);
        setPrix(prix);
    }
}
