/*
 * This file is generated by jOOQ.
 */
package generation.tables.records;


import generation.tables.UserRole;

import org.jooq.Field;
import org.jooq.Record2;
import org.jooq.Row2;
import org.jooq.impl.TableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class UserRoleRecord extends TableRecordImpl<UserRoleRecord> implements Record2<Integer, Integer> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>public.user_role.id_user</code>.
     */
    public void setIdUser(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>public.user_role.id_user</code>.
     */
    public Integer getIdUser() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>public.user_role.id_role</code>.
     */
    public void setIdRole(Integer value) {
        set(1, value);
    }

    /**
     * Getter for <code>public.user_role.id_role</code>.
     */
    public Integer getIdRole() {
        return (Integer) get(1);
    }

    // -------------------------------------------------------------------------
    // Record2 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row2<Integer, Integer> fieldsRow() {
        return (Row2) super.fieldsRow();
    }

    @Override
    public Row2<Integer, Integer> valuesRow() {
        return (Row2) super.valuesRow();
    }

    @Override
    public Field<Integer> field1() {
        return UserRole.USER_ROLE.ID_USER;
    }

    @Override
    public Field<Integer> field2() {
        return UserRole.USER_ROLE.ID_ROLE;
    }

    @Override
    public Integer component1() {
        return getIdUser();
    }

    @Override
    public Integer component2() {
        return getIdRole();
    }

    @Override
    public Integer value1() {
        return getIdUser();
    }

    @Override
    public Integer value2() {
        return getIdRole();
    }

    @Override
    public UserRoleRecord value1(Integer value) {
        setIdUser(value);
        return this;
    }

    @Override
    public UserRoleRecord value2(Integer value) {
        setIdRole(value);
        return this;
    }

    @Override
    public UserRoleRecord values(Integer value1, Integer value2) {
        value1(value1);
        value2(value2);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached UserRoleRecord
     */
    public UserRoleRecord() {
        super(UserRole.USER_ROLE);
    }

    /**
     * Create a detached, initialised UserRoleRecord
     */
    public UserRoleRecord(Integer idUser, Integer idRole) {
        super(UserRole.USER_ROLE);

        setIdUser(idUser);
        setIdRole(idRole);
    }
}
