/*
 * This file is generated by jOOQ.
 */
package generation.tables.pojos;


import java.io.Serializable;
import java.time.LocalDate;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Action implements Serializable {

    private static final long serialVersionUID = 1L;

    private String    commentaire;
    private LocalDate dateAction;
    private Integer   idUser;
    private Integer   id;

    public Action() {}

    public Action(Action value) {
        this.commentaire = value.commentaire;
        this.dateAction = value.dateAction;
        this.idUser = value.idUser;
        this.id = value.id;
    }

    public Action(
        String    commentaire,
        LocalDate dateAction,
        Integer   idUser,
        Integer   id
    ) {
        this.commentaire = commentaire;
        this.dateAction = dateAction;
        this.idUser = idUser;
        this.id = id;
    }

    /**
     * Getter for <code>public.action.commentaire</code>.
     */
    public String getCommentaire() {
        return this.commentaire;
    }

    /**
     * Setter for <code>public.action.commentaire</code>.
     */
    public void setCommentaire(String commentaire) {
        this.commentaire = commentaire;
    }

    /**
     * Getter for <code>public.action.date_action</code>.
     */
    public LocalDate getDateAction() {
        return this.dateAction;
    }

    /**
     * Setter for <code>public.action.date_action</code>.
     */
    public void setDateAction(LocalDate dateAction) {
        this.dateAction = dateAction;
    }

    /**
     * Getter for <code>public.action.id_user</code>.
     */
    public Integer getIdUser() {
        return this.idUser;
    }

    /**
     * Setter for <code>public.action.id_user</code>.
     */
    public void setIdUser(Integer idUser) {
        this.idUser = idUser;
    }

    /**
     * Getter for <code>public.action.id</code>.
     */
    public Integer getId() {
        return this.id;
    }

    /**
     * Setter for <code>public.action.id</code>.
     */
    public void setId(Integer id) {
        this.id = id;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("Action (");

        sb.append(commentaire);
        sb.append(", ").append(dateAction);
        sb.append(", ").append(idUser);
        sb.append(", ").append(id);

        sb.append(")");
        return sb.toString();
    }
}
