/*
 * This file is generated by jOOQ.
 */
package generation.tables.pojos;


import java.io.Serializable;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class ApplicationUser implements Serializable {

    private static final long serialVersionUID = 1L;

    private Integer id;
    private String  username;
    private String  nom;
    private String  password;
    private String  mail;
    private Boolean actif;

    public ApplicationUser() {}

    public ApplicationUser(ApplicationUser value) {
        this.id = value.id;
        this.username = value.username;
        this.nom = value.nom;
        this.password = value.password;
        this.mail = value.mail;
        this.actif = value.actif;
    }

    public ApplicationUser(
        Integer id,
        String  username,
        String  nom,
        String  password,
        String  mail,
        Boolean actif
    ) {
        this.id = id;
        this.username = username;
        this.nom = nom;
        this.password = password;
        this.mail = mail;
        this.actif = actif;
    }

    /**
     * Getter for <code>public.application_user.id</code>.
     */
    public Integer getId() {
        return this.id;
    }

    /**
     * Setter for <code>public.application_user.id</code>.
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * Getter for <code>public.application_user.username</code>.
     */
    public String getUsername() {
        return this.username;
    }

    /**
     * Setter for <code>public.application_user.username</code>.
     */
    public void setUsername(String username) {
        this.username = username;
    }

    /**
     * Getter for <code>public.application_user.nom</code>.
     */
    public String getNom() {
        return this.nom;
    }

    /**
     * Setter for <code>public.application_user.nom</code>.
     */
    public void setNom(String nom) {
        this.nom = nom;
    }

    /**
     * Getter for <code>public.application_user.password</code>.
     */
    public String getPassword() {
        return this.password;
    }

    /**
     * Setter for <code>public.application_user.password</code>.
     */
    public void setPassword(String password) {
        this.password = password;
    }

    /**
     * Getter for <code>public.application_user.mail</code>.
     */
    public String getMail() {
        return this.mail;
    }

    /**
     * Setter for <code>public.application_user.mail</code>.
     */
    public void setMail(String mail) {
        this.mail = mail;
    }

    /**
     * Getter for <code>public.application_user.actif</code>.
     */
    public Boolean getActif() {
        return this.actif;
    }

    /**
     * Setter for <code>public.application_user.actif</code>.
     */
    public void setActif(Boolean actif) {
        this.actif = actif;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("ApplicationUser (");

        sb.append(id);
        sb.append(", ").append(username);
        sb.append(", ").append(nom);
        sb.append(", ").append(password);
        sb.append(", ").append(mail);
        sb.append(", ").append(actif);

        sb.append(")");
        return sb.toString();
    }
}
