/*
 * This file is generated by jOOQ.
 */
package generation.tables.pojos;


import java.io.Serializable;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Auteur implements Serializable {

    private static final long serialVersionUID = 1L;

    private Integer id;
    private String  nom;
    private String  prenom;

    public Auteur() {}

    public Auteur(Auteur value) {
        this.id = value.id;
        this.nom = value.nom;
        this.prenom = value.prenom;
    }

    public Auteur(
        Integer id,
        String  nom,
        String  prenom
    ) {
        this.id = id;
        this.nom = nom;
        this.prenom = prenom;
    }

    /**
     * Getter for <code>PUBLIC.AUTEUR.ID</code>.
     */
    public Integer getId() {
        return this.id;
    }

    /**
     * Setter for <code>PUBLIC.AUTEUR.ID</code>.
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * Getter for <code>PUBLIC.AUTEUR.NOM</code>.
     */
    public String getNom() {
        return this.nom;
    }

    /**
     * Setter for <code>PUBLIC.AUTEUR.NOM</code>.
     */
    public void setNom(String nom) {
        this.nom = nom;
    }

    /**
     * Getter for <code>PUBLIC.AUTEUR.PRENOM</code>.
     */
    public String getPrenom() {
        return this.prenom;
    }

    /**
     * Setter for <code>PUBLIC.AUTEUR.PRENOM</code>.
     */
    public void setPrenom(String prenom) {
        this.prenom = prenom;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("Auteur (");

        sb.append(id);
        sb.append(", ").append(nom);
        sb.append(", ").append(prenom);

        sb.append(")");
        return sb.toString();
    }
}
