/*
 * This file is generated by jOOQ.
 */
package generation.tables.pojos;


import java.io.Serializable;
import java.time.LocalDate;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Profil implements Serializable {

    private static final long serialVersionUID = 1L;

    private Integer   id;
    private LocalDate datePublication;
    private String    genre;

    public Profil() {}

    public Profil(Profil value) {
        this.id = value.id;
        this.datePublication = value.datePublication;
        this.genre = value.genre;
    }

    public Profil(
        Integer   id,
        LocalDate datePublication,
        String    genre
    ) {
        this.id = id;
        this.datePublication = datePublication;
        this.genre = genre;
    }

    /**
     * Getter for <code>public.profil.id</code>.
     */
    public Integer getId() {
        return this.id;
    }

    /**
     * Setter for <code>public.profil.id</code>.
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * Getter for <code>public.profil.date_publication</code>.
     */
    public LocalDate getDatePublication() {
        return this.datePublication;
    }

    /**
     * Setter for <code>public.profil.date_publication</code>.
     */
    public void setDatePublication(LocalDate datePublication) {
        this.datePublication = datePublication;
    }

    /**
     * Getter for <code>public.profil.genre</code>.
     */
    public String getGenre() {
        return this.genre;
    }

    /**
     * Setter for <code>public.profil.genre</code>.
     */
    public void setGenre(String genre) {
        this.genre = genre;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("Profil (");

        sb.append(id);
        sb.append(", ").append(datePublication);
        sb.append(", ").append(genre);

        sb.append(")");
        return sb.toString();
    }
}
