/*
 * This file is generated by jOOQ.
 */
package generation.tables.pojos;


import java.io.Serializable;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Role implements Serializable {

    private static final long serialVersionUID = 1L;

    private Integer id;
    private String  nom;
    private String  description;

    public Role() {}

    public Role(Role value) {
        this.id = value.id;
        this.nom = value.nom;
        this.description = value.description;
    }

    public Role(
        Integer id,
        String  nom,
        String  description
    ) {
        this.id = id;
        this.nom = nom;
        this.description = description;
    }

    /**
     * Getter for <code>public.role.id</code>.
     */
    public Integer getId() {
        return this.id;
    }

    /**
     * Setter for <code>public.role.id</code>.
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * Getter for <code>public.role.nom</code>.
     */
    public String getNom() {
        return this.nom;
    }

    /**
     * Setter for <code>public.role.nom</code>.
     */
    public void setNom(String nom) {
        this.nom = nom;
    }

    /**
     * Getter for <code>public.role.description</code>.
     */
    public String getDescription() {
        return this.description;
    }

    /**
     * Setter for <code>public.role.description</code>.
     */
    public void setDescription(String description) {
        this.description = description;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("Role (");

        sb.append(id);
        sb.append(", ").append(nom);
        sb.append(", ").append(description);

        sb.append(")");
        return sb.toString();
    }
}
