/*
 * This file is generated by jOOQ.
 */
package generation.tables.pojos;


import java.io.Serializable;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class UserRole implements Serializable {

    private static final long serialVersionUID = 1L;

    private Integer idUser;
    private Integer idRole;

    public UserRole() {}

    public UserRole(UserRole value) {
        this.idUser = value.idUser;
        this.idRole = value.idRole;
    }

    public UserRole(
        Integer idUser,
        Integer idRole
    ) {
        this.idUser = idUser;
        this.idRole = idRole;
    }

    /**
     * Getter for <code>public.user_role.id_user</code>.
     */
    public Integer getIdUser() {
        return this.idUser;
    }

    /**
     * Setter for <code>public.user_role.id_user</code>.
     */
    public void setIdUser(Integer idUser) {
        this.idUser = idUser;
    }

    /**
     * Getter for <code>public.user_role.id_role</code>.
     */
    public Integer getIdRole() {
        return this.idRole;
    }

    /**
     * Setter for <code>public.user_role.id_role</code>.
     */
    public void setIdRole(Integer idRole) {
        this.idRole = idRole;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("UserRole (");

        sb.append(idUser);
        sb.append(", ").append(idRole);

        sb.append(")");
        return sb.toString();
    }
}
