/*
 * This file is generated by jOOQ.
 */
package generation.tables.pojos;


import java.io.Serializable;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class UserLivre implements Serializable {

    private static final long serialVersionUID = 1L;

    private Integer idLivre;
    private Integer idUser;

    public UserLivre() {}

    public UserLivre(UserLivre value) {
        this.idLivre = value.idLivre;
        this.idUser = value.idUser;
    }

    public UserLivre(
        Integer idLivre,
        Integer idUser
    ) {
        this.idLivre = idLivre;
        this.idUser = idUser;
    }

    /**
     * Getter for <code>public.user_livre.id_livre</code>.
     */
    public Integer getIdLivre() {
        return this.idLivre;
    }

    /**
     * Setter for <code>public.user_livre.id_livre</code>.
     */
    public void setIdLivre(Integer idLivre) {
        this.idLivre = idLivre;
    }

    /**
     * Getter for <code>public.user_livre.id_user</code>.
     */
    public Integer getIdUser() {
        return this.idUser;
    }

    /**
     * Setter for <code>public.user_livre.id_user</code>.
     */
    public void setIdUser(Integer idUser) {
        this.idUser = idUser;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("UserLivre (");

        sb.append(idLivre);
        sb.append(", ").append(idUser);

        sb.append(")");
        return sb.toString();
    }
}
