/*
 * This file is generated by jOOQ.
 */
package generation;


import generation.tables.Auteur;
import generation.tables.Livre;
import generation.tables.Profil;


/**
 * Convenience access to all tables in PUBLIC.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

    /**
     * The table <code>PUBLIC.AUTEUR</code>.
     */
    public static final Auteur AUTEUR = Auteur.AUTEUR;

    /**
     * The table <code>PUBLIC.LIVRE</code>.
     */
    public static final Livre LIVRE = Livre.LIVRE;

    /**
     * The table <code>PUBLIC.PROFIL</code>.
     */
    public static final Profil PROFIL = Profil.PROFIL;
}
